#!/bin/bash

\rm -rf YU* OUTPUT fort.*  M_* core script_*.grc stdeo_*.grc grc.nqs *.tex

mkdir -p output/1h output/1h_clearsky output/1h_rad output/1h_second output/1h_vertint output/3h output/6h output/24h output/6h_3D output/6h_3D_second output/restarts output/job_logs
