#!/bin/bash

# setup defaults
if [ -z "${NPX_LM2LM}" ]; then
  NPX=3
else
  NPX=${NPX_LM2LM}
fi
if [ -z "${NPY_LM2LM}" ]; then
  NPY=7
else
  NPY=${NPY_LM2LM}
fi
if [ -z "${NPIO_LM2LM}" ]; then
  NPIO=1
else
  NPIO=${NPIO_LM2LM}
fi
if [ -z "${EXE_LM2LM}" ]; then
  EXE=int2lm
else
  EXE=${EXE_LM2LM}
fi
if [ -z "$1" ]; then
  SCHEDULER="SLURM"
else
  SCHEDULER="$1"
fi
if [ -z "$2" ]; then
  QUEUE="normal"
else
  QUEUE="$2"
fi
if [ -z "$3" ]; then
  ACCOUNT="ch4"
else
  ACCOUNT="$3"
fi
if [ -z "$4" ]; then
  WAITFORJOB=""
else
  WAITFORJOB="$4"
fi
HOST=`hostname | sed 's/\..*$//g' | sed 's/[0-9]*$//g'`

# check scheduler
if [ "${SCHEDULER}" != "SLURM" ]; then
  echo "ERROR: unsupported scheduler (${SCHEDULER})"
  exit 1
fi

# compute derived variables
NTASKS=`echo "${NPX}"'*'"${NPY}"'+'"${NPIO}" | bc`

# cleanup
if [ -f .jobid ]; then
  $(squeue -j `cat .jobid` &>/dev/null) && scancel `cat .jobid`
  sleep 3
  \rm .jobid 2>/dev/null
fi
./clean

# setup namelists
cat > INPUT <<EOF
  &CONTRL
  hincbound=1.0,
  hstart=${LM_NL_HSTART},
  hstop=${LM_NL_HSTOP},
  nprocx=${NPX}, nprocy=${NPY}, nprocio=${NPIO},
  ydate_ini='${LM_YYYY_INI}${LM_MM_INI}${LM_DD_INI}${LM_ZZ_INI}0000',
  ydate_bd ='${LM_YYYY_INI}${LM_MM_INI}${LM_DD_INI}${LM_ZZ_INI}0000',
  lmixcld=.false.,
  yinput_model = 'COSMO'
  linitial = .TRUE.,
  idbg_level=3,
  luse_t_skin=.TRUE.,
  nincwait=30,
  nmaxwait=300,
  lboundaries=.true.,
  lprog_qi=.true.,
  lprog_qr_qs=.true.,
  lprog_rho_snow=.false.,
  lmulti_layer_in=.true.,
  lmulti_layer_lm=.true.,
  itype_w_so_rel=1,
  lforest=.TRUE., lsso=.TRUE.,
  lvertwind_ini=.true.,
  lvertwind_bd=.false.,
  llbc_smooth=.true.,
    lfilter_pp=.true.,
  lfilter_oro=.FALSE.,
    ilow_pass_oro=4,
      numfilt_oro=1,
      ilow_pass_xso=5,
        lxso_first=.FALSE.,
        numfilt_xso=1,
        rxso_mask=750.0,
    eps_filter=0.1,
      norder_filter=5,
    l_topo_z=.false.,
  l_s_oro=.TRUE.,
  rfill_valley=0.0,
    ifill_valley=7,
  ltime_mean=.true.,
  lreorder=.false.,
  lasync_io=.FALSE.,
  lbdclim=.TRUE.,
  itype_aerosol = 2,
  itype_albedo = 2,  
  /END
 &GRID_IN
  pcontrol_fi = 30000.,
  ie_in_tot = 551, je_in_tot = 361, ke_in_tot = 60,
  startlat_in_tot  = -12.26, startlon_in_tot  = -70.115,
  pollat_in = 90.0, pollon_in = -180.0,
  dlat_in = 0.11, dlon_in = 0.11,
  endlon_in_tot=13.86, endlat_in_tot=15.51,
  ke_soil_in=9,
  czml_soil_in=0.005, 0.025, 0.07, 0.16, 0.34, 0.70, 1.47, 2.86, 5.74, 11.50,
 /END
 &LMGRID
  ielm_tot=2310, jelm_tot=1542, kelm_tot=60,
  ivctype=2, vcflat = 11357.0,
  ke_soil_lm=9, irefatm=2,
  czml_soil_lm=0.005, 0.025, 0.07, 0.16, 0.34, 0.70, 1.47, 2.86, 5.74,  11.50,
  vcoord_d=29798.50,28255.93,26824.04,   25497.39,   24269.35,
     23134.03,   22081.88,   21105.64,   20207.79,   19360.60,
     18576.52,   17827.86,   17127.98,   16451.10,   15811.52,
     15183.53,   14581.37,   13982.04,   13400.03,   12815.37,
     12248.19,   11678.54,   11126.48,   10572.09,   10035.43,
      9496.58,    8975.59,    8452.55,    7947.52,    7440.55,
      6931.96,    6442.38,    5956.41,    5498.04,    5050.84,
      4647.96,    4261.91,    3893.26,    3542.15,    3208.52,
      2892.23,    2593.71,    2312.95,    2049.75,    1803.89,
      1575.57,    1364.68,    1170.90,     993.84,     833.44,
       689.53,     561.52,     448.82,     350.95,     267.55,
       197.67,     137.23,      87.33,      48.44,      20.00,       0.00,
  pollat = 90.0 , pollon = -180.0,
  dlon=0.02, dlat=0.02,
  startlat_tot  = -7.77,
  startlon_tot  = -65.625,
 /END
 &DATABASE
 /END
 &DATA
  ylmext_form_read='ncdf',
  yinext_form_read='ncdf',
  yin_form_read='ncdf',
  ylm_form_write='ncdf',
  ie_ext=2990, je_ext=1900,
  ylmext_lfn='./input/extpar_atlantic_2km.nc',
  ylmext_cat='./',
  yinext_lfn='lffd${LM_YYYY_INI}${LM_MM_INI}${LM_DD_INI}${LM_ZZ_INI}0000c.nc',
  yinext_cat='./input/',
  yin_cat='./input/',
  ylm_cat= './output/',
  nprocess_ini = 131, nprocess_bd = 132,
  yinput_type='forecast',
  ytunit_in='d',
  ytunit_out='d',
 /END
 &PRICTR
  igp_tot = 36, 40, 48, 44, 48, 85, 77,
  jgp_tot = 30, 94, 38, 26, 26, 96, 12,
  lchkin=.TRUE., lchkout=.TRUE.,lprgp=.FALSE.,
 /END
EOF

# setup job
cat > job <<EOF_job_SLURM
#!/bin/tcsh
#SBATCH --job-name=lm2lm
#SBATCH --output=job.out
#SBATCH --ntasks=${NTASKS}
#SBATCH --partition=${QUEUE}
#SBATCH --time=10:30:00
#SBATCH --account=${ACCOUNT}
EOF_job_SLURM

#We currently only have an allocation on GPU nodes
if [[ $HOST == daint* ]]; then
  sed -i '/account=/a\
#SBATCH --constraint=gpu\
module load daint-gpu' job
fi

# rest of job (actual work)
cat >> job <<EOF_job

# Initialization
set verbose
set echo

# set environmental parameters
setenv OMP_NUM_THREADS 1
setenv MALLOC_MMAP_MAX_ 0
setenv MALLOC_TRIM_THRESHOLD_ 536870912
setenv MPICH_RDMA_ENABLED_CUDA 0
setenv MV2_USE_CUDA 0

# cleanup
./clean

# echo date
date

# Run LM in case directory
${RUNCMD} -u -n ${NTASKS} ${EXE}

# echo date
date

# do postprocessing
cd ./output/
../../bin/grc
cd -

# remove job tag (if present)
\rm -f .jobid >&/dev/null
sacct -j \$SLURM_JOB_ID --format=User,JobID,Jobname,partition,state,time,start,end,elapsed,MaxRss,MaxVMSize,nnodes,ncpus,nodelist,AveC
PUFreq
# done
EOF_job

# clean away old *.out files
\rm -f *.out 2>/dev/null

if [ -z "${WAITFORJOB}" ]; then
  jobid=`sbatch -C gpu job | sed 's/Submitted batch job //g'`
else
  jobid=`sbatch -C gpu --dependency=after:${WAITFORJOB} job | sed 's/Submitted batch job //g'`
fi

if [ $? -eq 0 -a -n "${jobid}" ]; then
  echo "${jobid}" > .jobid
  echo "${jobid}"
else
  exit 1
fi

